services:
  ejschallenge:
    image: ejschallenge
    build:
      context: Task 2/blogWebsite-main
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
